// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// LimiterMock is a mock implementation of graphql.Limiter.
//
//	func TestSomethingThatUsesLimiter(t *testing.T) {
//
//		// make and configure a mocked graphql.Limiter
//		mockedLimiter := &LimiterMock{
//			WaitFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Wait method")
//			},
//		}
//
//		// use mockedLimiter in code that requires graphql.Limiter
//		// and then make assertions.
//
//	}
type LimiterMock struct {
	// WaitFunc mocks the Wait method.
	WaitFunc func(contextMoqParam context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Wait holds details about calls to the Wait method.
		Wait []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockWait sync.RWMutex
}

// Wait calls WaitFunc.
func (mock *LimiterMock) Wait(contextMoqParam context.Context) error {
	if mock.WaitFunc == nil {
		panic("LimiterMock.WaitFunc: method is nil but Limiter.Wait was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockWait.Lock()
	mock.calls.Wait = append(mock.calls.Wait, callInfo)
	mock.lockWait.Unlock()
	return mock.WaitFunc(contextMoqParam)
}

// WaitCalls gets all the calls that were made to Wait.
// Check the length with:
//
//	len(mockedLimiter.WaitCalls())
func (mock *LimiterMock) WaitCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockWait.RLock()
	calls = mock.calls.Wait
	mock.lockWait.RUnlock()
	return calls
}

// ResetWaitCalls reset all the calls that were made to Wait.
func (mock *LimiterMock) ResetWaitCalls() {
	mock.lockWait.Lock()
	mock.calls.Wait = nil
	mock.lockWait.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *LimiterMock) ResetCalls() {
	mock.lockWait.Lock()
	mock.calls.Wait = nil
	mock.lockWait.Unlock()
}
