// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"net/http"
	"sync"
)

// RoundTripperMock is a mock implementation of graphql.RoundTripper.
//
//	func TestSomethingThatUsesRoundTripper(t *testing.T) {
//
//		// make and configure a mocked graphql.RoundTripper
//		mockedRoundTripper := &RoundTripperMock{
//			RoundTripFunc: func(request *http.Request) (*http.Response, error) {
//				panic("mock out the RoundTrip method")
//			},
//		}
//
//		// use mockedRoundTripper in code that requires graphql.RoundTripper
//		// and then make assertions.
//
//	}
type RoundTripperMock struct {
	// RoundTripFunc mocks the RoundTrip method.
	RoundTripFunc func(request *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// RoundTrip holds details about calls to the RoundTrip method.
		RoundTrip []struct {
			// Request is the request argument value.
			Request *http.Request
		}
	}
	lockRoundTrip sync.RWMutex
}

// RoundTrip calls RoundTripFunc.
func (mock *RoundTripperMock) RoundTrip(request *http.Request) (*http.Response, error) {
	if mock.RoundTripFunc == nil {
		panic("RoundTripperMock.RoundTripFunc: method is nil but RoundTripper.RoundTrip was just called")
	}
	callInfo := struct {
		Request *http.Request
	}{
		Request: request,
	}
	mock.lockRoundTrip.Lock()
	mock.calls.RoundTrip = append(mock.calls.RoundTrip, callInfo)
	mock.lockRoundTrip.Unlock()
	return mock.RoundTripFunc(request)
}

// RoundTripCalls gets all the calls that were made to RoundTrip.
// Check the length with:
//
//	len(mockedRoundTripper.RoundTripCalls())
func (mock *RoundTripperMock) RoundTripCalls() []struct {
	Request *http.Request
} {
	var calls []struct {
		Request *http.Request
	}
	mock.lockRoundTrip.RLock()
	calls = mock.calls.RoundTrip
	mock.lockRoundTrip.RUnlock()
	return calls
}

// ResetRoundTripCalls reset all the calls that were made to RoundTrip.
func (mock *RoundTripperMock) ResetRoundTripCalls() {
	mock.lockRoundTrip.Lock()
	mock.calls.RoundTrip = nil
	mock.lockRoundTrip.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *RoundTripperMock) ResetCalls() {
	mock.lockRoundTrip.Lock()
	mock.calls.RoundTrip = nil
	mock.lockRoundTrip.Unlock()
}
