// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/feed-relay/rsscast"
	"github.com/feed-relay/smotrim/internal/api"
	"github.com/feed-relay/smotrim/internal/api/graphql"
)

// AdapterMock is a mock implementation of provider.Adapter.
//
//	func TestSomethingThatUsesAdapter(t *testing.T) {
//
//		// make and configure a mocked provider.Adapter
//		mockedAdapter := &AdapterMock{
//			FeedFunc: func(ctx context.Context, channel *graphql.Channel, brand *graphql.Brand, episodes []*graphql.Episode, audios map[int]*api.Audio) (*rsscast.Feed, error) {
//				panic("mock out the Feed method")
//			},
//		}
//
//		// use mockedAdapter in code that requires provider.Adapter
//		// and then make assertions.
//
//	}
type AdapterMock struct {
	// FeedFunc mocks the Feed method.
	FeedFunc func(ctx context.Context, channel *graphql.Channel, brand *graphql.Brand, episodes []*graphql.Episode, audios map[int]*api.Audio) (*rsscast.Feed, error)

	// calls tracks calls to the methods.
	calls struct {
		// Feed holds details about calls to the Feed method.
		Feed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Channel is the channel argument value.
			Channel *graphql.Channel
			// Brand is the brand argument value.
			Brand *graphql.Brand
			// Episodes is the episodes argument value.
			Episodes []*graphql.Episode
			// Audios is the audios argument value.
			Audios map[int]*api.Audio
		}
	}
	lockFeed sync.RWMutex
}

// Feed calls FeedFunc.
func (mock *AdapterMock) Feed(ctx context.Context, channel *graphql.Channel, brand *graphql.Brand, episodes []*graphql.Episode, audios map[int]*api.Audio) (*rsscast.Feed, error) {
	if mock.FeedFunc == nil {
		panic("AdapterMock.FeedFunc: method is nil but Adapter.Feed was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Channel  *graphql.Channel
		Brand    *graphql.Brand
		Episodes []*graphql.Episode
		Audios   map[int]*api.Audio
	}{
		Ctx:      ctx,
		Channel:  channel,
		Brand:    brand,
		Episodes: episodes,
		Audios:   audios,
	}
	mock.lockFeed.Lock()
	mock.calls.Feed = append(mock.calls.Feed, callInfo)
	mock.lockFeed.Unlock()
	return mock.FeedFunc(ctx, channel, brand, episodes, audios)
}

// FeedCalls gets all the calls that were made to Feed.
// Check the length with:
//
//	len(mockedAdapter.FeedCalls())
func (mock *AdapterMock) FeedCalls() []struct {
	Ctx      context.Context
	Channel  *graphql.Channel
	Brand    *graphql.Brand
	Episodes []*graphql.Episode
	Audios   map[int]*api.Audio
} {
	var calls []struct {
		Ctx      context.Context
		Channel  *graphql.Channel
		Brand    *graphql.Brand
		Episodes []*graphql.Episode
		Audios   map[int]*api.Audio
	}
	mock.lockFeed.RLock()
	calls = mock.calls.Feed
	mock.lockFeed.RUnlock()
	return calls
}

// ResetFeedCalls reset all the calls that were made to Feed.
func (mock *AdapterMock) ResetFeedCalls() {
	mock.lockFeed.Lock()
	mock.calls.Feed = nil
	mock.lockFeed.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *AdapterMock) ResetCalls() {
	mock.lockFeed.Lock()
	mock.calls.Feed = nil
	mock.lockFeed.Unlock()
}
