// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"time"
)

// ConfigMock is a mock implementation of provider.Config.
//
//	func TestSomethingThatUsesConfig(t *testing.T) {
//
//		// make and configure a mocked provider.Config
//		mockedConfig := &ConfigMock{
//			GeneratorFunc: func() string {
//				panic("mock out the Generator method")
//			},
//			HTTPTimeoutFunc: func() time.Duration {
//				panic("mock out the HTTPTimeout method")
//			},
//			ItunesOwnerEmailFunc: func() string {
//				panic("mock out the ItunesOwnerEmail method")
//			},
//			ItunesOwnerNameFunc: func() string {
//				panic("mock out the ItunesOwnerName method")
//			},
//			TestDataFunc: func() bool {
//				panic("mock out the TestData method")
//			},
//		}
//
//		// use mockedConfig in code that requires provider.Config
//		// and then make assertions.
//
//	}
type ConfigMock struct {
	// GeneratorFunc mocks the Generator method.
	GeneratorFunc func() string

	// HTTPTimeoutFunc mocks the HTTPTimeout method.
	HTTPTimeoutFunc func() time.Duration

	// ItunesOwnerEmailFunc mocks the ItunesOwnerEmail method.
	ItunesOwnerEmailFunc func() string

	// ItunesOwnerNameFunc mocks the ItunesOwnerName method.
	ItunesOwnerNameFunc func() string

	// TestDataFunc mocks the TestData method.
	TestDataFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// Generator holds details about calls to the Generator method.
		Generator []struct {
		}
		// HTTPTimeout holds details about calls to the HTTPTimeout method.
		HTTPTimeout []struct {
		}
		// ItunesOwnerEmail holds details about calls to the ItunesOwnerEmail method.
		ItunesOwnerEmail []struct {
		}
		// ItunesOwnerName holds details about calls to the ItunesOwnerName method.
		ItunesOwnerName []struct {
		}
		// TestData holds details about calls to the TestData method.
		TestData []struct {
		}
	}
	lockGenerator        sync.RWMutex
	lockHTTPTimeout      sync.RWMutex
	lockItunesOwnerEmail sync.RWMutex
	lockItunesOwnerName  sync.RWMutex
	lockTestData         sync.RWMutex
}

// Generator calls GeneratorFunc.
func (mock *ConfigMock) Generator() string {
	if mock.GeneratorFunc == nil {
		panic("ConfigMock.GeneratorFunc: method is nil but Config.Generator was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGenerator.Lock()
	mock.calls.Generator = append(mock.calls.Generator, callInfo)
	mock.lockGenerator.Unlock()
	return mock.GeneratorFunc()
}

// GeneratorCalls gets all the calls that were made to Generator.
// Check the length with:
//
//	len(mockedConfig.GeneratorCalls())
func (mock *ConfigMock) GeneratorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGenerator.RLock()
	calls = mock.calls.Generator
	mock.lockGenerator.RUnlock()
	return calls
}

// ResetGeneratorCalls reset all the calls that were made to Generator.
func (mock *ConfigMock) ResetGeneratorCalls() {
	mock.lockGenerator.Lock()
	mock.calls.Generator = nil
	mock.lockGenerator.Unlock()
}

// HTTPTimeout calls HTTPTimeoutFunc.
func (mock *ConfigMock) HTTPTimeout() time.Duration {
	if mock.HTTPTimeoutFunc == nil {
		panic("ConfigMock.HTTPTimeoutFunc: method is nil but Config.HTTPTimeout was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHTTPTimeout.Lock()
	mock.calls.HTTPTimeout = append(mock.calls.HTTPTimeout, callInfo)
	mock.lockHTTPTimeout.Unlock()
	return mock.HTTPTimeoutFunc()
}

// HTTPTimeoutCalls gets all the calls that were made to HTTPTimeout.
// Check the length with:
//
//	len(mockedConfig.HTTPTimeoutCalls())
func (mock *ConfigMock) HTTPTimeoutCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHTTPTimeout.RLock()
	calls = mock.calls.HTTPTimeout
	mock.lockHTTPTimeout.RUnlock()
	return calls
}

// ResetHTTPTimeoutCalls reset all the calls that were made to HTTPTimeout.
func (mock *ConfigMock) ResetHTTPTimeoutCalls() {
	mock.lockHTTPTimeout.Lock()
	mock.calls.HTTPTimeout = nil
	mock.lockHTTPTimeout.Unlock()
}

// ItunesOwnerEmail calls ItunesOwnerEmailFunc.
func (mock *ConfigMock) ItunesOwnerEmail() string {
	if mock.ItunesOwnerEmailFunc == nil {
		panic("ConfigMock.ItunesOwnerEmailFunc: method is nil but Config.ItunesOwnerEmail was just called")
	}
	callInfo := struct {
	}{}
	mock.lockItunesOwnerEmail.Lock()
	mock.calls.ItunesOwnerEmail = append(mock.calls.ItunesOwnerEmail, callInfo)
	mock.lockItunesOwnerEmail.Unlock()
	return mock.ItunesOwnerEmailFunc()
}

// ItunesOwnerEmailCalls gets all the calls that were made to ItunesOwnerEmail.
// Check the length with:
//
//	len(mockedConfig.ItunesOwnerEmailCalls())
func (mock *ConfigMock) ItunesOwnerEmailCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockItunesOwnerEmail.RLock()
	calls = mock.calls.ItunesOwnerEmail
	mock.lockItunesOwnerEmail.RUnlock()
	return calls
}

// ResetItunesOwnerEmailCalls reset all the calls that were made to ItunesOwnerEmail.
func (mock *ConfigMock) ResetItunesOwnerEmailCalls() {
	mock.lockItunesOwnerEmail.Lock()
	mock.calls.ItunesOwnerEmail = nil
	mock.lockItunesOwnerEmail.Unlock()
}

// ItunesOwnerName calls ItunesOwnerNameFunc.
func (mock *ConfigMock) ItunesOwnerName() string {
	if mock.ItunesOwnerNameFunc == nil {
		panic("ConfigMock.ItunesOwnerNameFunc: method is nil but Config.ItunesOwnerName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockItunesOwnerName.Lock()
	mock.calls.ItunesOwnerName = append(mock.calls.ItunesOwnerName, callInfo)
	mock.lockItunesOwnerName.Unlock()
	return mock.ItunesOwnerNameFunc()
}

// ItunesOwnerNameCalls gets all the calls that were made to ItunesOwnerName.
// Check the length with:
//
//	len(mockedConfig.ItunesOwnerNameCalls())
func (mock *ConfigMock) ItunesOwnerNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockItunesOwnerName.RLock()
	calls = mock.calls.ItunesOwnerName
	mock.lockItunesOwnerName.RUnlock()
	return calls
}

// ResetItunesOwnerNameCalls reset all the calls that were made to ItunesOwnerName.
func (mock *ConfigMock) ResetItunesOwnerNameCalls() {
	mock.lockItunesOwnerName.Lock()
	mock.calls.ItunesOwnerName = nil
	mock.lockItunesOwnerName.Unlock()
}

// TestData calls TestDataFunc.
func (mock *ConfigMock) TestData() bool {
	if mock.TestDataFunc == nil {
		panic("ConfigMock.TestDataFunc: method is nil but Config.TestData was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTestData.Lock()
	mock.calls.TestData = append(mock.calls.TestData, callInfo)
	mock.lockTestData.Unlock()
	return mock.TestDataFunc()
}

// TestDataCalls gets all the calls that were made to TestData.
// Check the length with:
//
//	len(mockedConfig.TestDataCalls())
func (mock *ConfigMock) TestDataCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTestData.RLock()
	calls = mock.calls.TestData
	mock.lockTestData.RUnlock()
	return calls
}

// ResetTestDataCalls reset all the calls that were made to TestData.
func (mock *ConfigMock) ResetTestDataCalls() {
	mock.lockTestData.Lock()
	mock.calls.TestData = nil
	mock.lockTestData.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ConfigMock) ResetCalls() {
	mock.lockGenerator.Lock()
	mock.calls.Generator = nil
	mock.lockGenerator.Unlock()

	mock.lockHTTPTimeout.Lock()
	mock.calls.HTTPTimeout = nil
	mock.lockHTTPTimeout.Unlock()

	mock.lockItunesOwnerEmail.Lock()
	mock.calls.ItunesOwnerEmail = nil
	mock.lockItunesOwnerEmail.Unlock()

	mock.lockItunesOwnerName.Lock()
	mock.calls.ItunesOwnerName = nil
	mock.lockItunesOwnerName.Unlock()

	mock.lockTestData.Lock()
	mock.calls.TestData = nil
	mock.lockTestData.Unlock()
}
