// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// SubMock is a mock implementation of provider.Sub.
//
//	func TestSomethingThatUsesSub(t *testing.T) {
//
//		// make and configure a mocked provider.Sub
//		mockedSub := &SubMock{
//			LimitFunc: func() int {
//				panic("mock out the Limit method")
//			},
//			ShowsFunc: func() []string {
//				panic("mock out the Shows method")
//			},
//		}
//
//		// use mockedSub in code that requires provider.Sub
//		// and then make assertions.
//
//	}
type SubMock struct {
	// LimitFunc mocks the Limit method.
	LimitFunc func() int

	// ShowsFunc mocks the Shows method.
	ShowsFunc func() []string

	// calls tracks calls to the methods.
	calls struct {
		// Limit holds details about calls to the Limit method.
		Limit []struct {
		}
		// Shows holds details about calls to the Shows method.
		Shows []struct {
		}
	}
	lockLimit sync.RWMutex
	lockShows sync.RWMutex
}

// Limit calls LimitFunc.
func (mock *SubMock) Limit() int {
	if mock.LimitFunc == nil {
		panic("SubMock.LimitFunc: method is nil but Sub.Limit was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLimit.Lock()
	mock.calls.Limit = append(mock.calls.Limit, callInfo)
	mock.lockLimit.Unlock()
	return mock.LimitFunc()
}

// LimitCalls gets all the calls that were made to Limit.
// Check the length with:
//
//	len(mockedSub.LimitCalls())
func (mock *SubMock) LimitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLimit.RLock()
	calls = mock.calls.Limit
	mock.lockLimit.RUnlock()
	return calls
}

// ResetLimitCalls reset all the calls that were made to Limit.
func (mock *SubMock) ResetLimitCalls() {
	mock.lockLimit.Lock()
	mock.calls.Limit = nil
	mock.lockLimit.Unlock()
}

// Shows calls ShowsFunc.
func (mock *SubMock) Shows() []string {
	if mock.ShowsFunc == nil {
		panic("SubMock.ShowsFunc: method is nil but Sub.Shows was just called")
	}
	callInfo := struct {
	}{}
	mock.lockShows.Lock()
	mock.calls.Shows = append(mock.calls.Shows, callInfo)
	mock.lockShows.Unlock()
	return mock.ShowsFunc()
}

// ShowsCalls gets all the calls that were made to Shows.
// Check the length with:
//
//	len(mockedSub.ShowsCalls())
func (mock *SubMock) ShowsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShows.RLock()
	calls = mock.calls.Shows
	mock.lockShows.RUnlock()
	return calls
}

// ResetShowsCalls reset all the calls that were made to Shows.
func (mock *SubMock) ResetShowsCalls() {
	mock.lockShows.Lock()
	mock.calls.Shows = nil
	mock.lockShows.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *SubMock) ResetCalls() {
	mock.lockLimit.Lock()
	mock.calls.Limit = nil
	mock.lockLimit.Unlock()

	mock.lockShows.Lock()
	mock.calls.Shows = nil
	mock.lockShows.Unlock()
}
