logger:
  level: debug
  format: json
  output: both
  add_source: false
  file_path: var/log/log.log
  rotation:
    max_size_mb: 100
    max_backups: 3
    max_age_days: 28
    compress: true
  fields:
    service: fr-smotrim

http:
  timeout: 60s

test_data: true
output_dir: var/rss
itunes_owner_name: "Feed Relay Smotrim"
itunes_owner_email: "feed-relay@example.com"
generator: "Feed Relay Smotrim v0.2.0 (github.com/feed-relay/smotrim)"

subscriptions:
  - limit: 5
    shows:
      - "https://smotrim.ru/brand/57166" # radiorus: О животных с Иваном Затевахиным
      - "57128" # radiorus: Литературный сериал

  - limit: 3
    shows:
      - "67390" # radiorus: Имя и время
      - "62250" # mayak: Физики и лирики
      - "65319" # mayak: АудиоСторис

feeds:
  # Радио России Санкт-Петербург
  - slug: "radiorus-spb"
    limit_per_show: 2
    shows:
      - "75260" # Спб - Дар слова
      - "75396" # Спб - Детский остров
      - "75252" # Спб - За чашкой кофе
      - "75275" # Спб - Как это по-русски?
      - "75226" # Спб - Любимые мелодии
      - "75439" # Спб - Невское утро
      - "75353" # Спб - Несгораемый шкаф
      - "75732" # Спб - Петербургский автограф
      - "75234" # Спб - Радиоклуб на Карповке
      - "75279" # Спб - Городской наблюдатель
      - "75223" # Спб - Пулковский меридиан