// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/feed-relay/smotrim/internal/api/graphql"
)

// ClientMock is a mock implementation of service.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked service.Client
//		mockedClient := &ClientMock{
//			BrandsRawFunc: func(ctx context.Context, limit int, page int) (*graphql.BrandsRaw, error) {
//				panic("mock out the BrandsRaw method")
//			},
//		}
//
//		// use mockedClient in code that requires service.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// BrandsRawFunc mocks the BrandsRaw method.
	BrandsRawFunc func(ctx context.Context, limit int, page int) (*graphql.BrandsRaw, error)

	// calls tracks calls to the methods.
	calls struct {
		// BrandsRaw holds details about calls to the BrandsRaw method.
		BrandsRaw []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Page is the page argument value.
			Page int
		}
	}
	lockBrandsRaw sync.RWMutex
}

// BrandsRaw calls BrandsRawFunc.
func (mock *ClientMock) BrandsRaw(ctx context.Context, limit int, page int) (*graphql.BrandsRaw, error) {
	if mock.BrandsRawFunc == nil {
		panic("ClientMock.BrandsRawFunc: method is nil but Client.BrandsRaw was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Limit int
		Page  int
	}{
		Ctx:   ctx,
		Limit: limit,
		Page:  page,
	}
	mock.lockBrandsRaw.Lock()
	mock.calls.BrandsRaw = append(mock.calls.BrandsRaw, callInfo)
	mock.lockBrandsRaw.Unlock()
	return mock.BrandsRawFunc(ctx, limit, page)
}

// BrandsRawCalls gets all the calls that were made to BrandsRaw.
// Check the length with:
//
//	len(mockedClient.BrandsRawCalls())
func (mock *ClientMock) BrandsRawCalls() []struct {
	Ctx   context.Context
	Limit int
	Page  int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
		Page  int
	}
	mock.lockBrandsRaw.RLock()
	calls = mock.calls.BrandsRaw
	mock.lockBrandsRaw.RUnlock()
	return calls
}

// ResetBrandsRawCalls reset all the calls that were made to BrandsRaw.
func (mock *ClientMock) ResetBrandsRawCalls() {
	mock.lockBrandsRaw.Lock()
	mock.calls.BrandsRaw = nil
	mock.lockBrandsRaw.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ClientMock) ResetCalls() {
	mock.lockBrandsRaw.Lock()
	mock.calls.BrandsRaw = nil
	mock.lockBrandsRaw.Unlock()
}
