// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"time"
)

// ConfigMock is a mock implementation of service.Config.
//
//	func TestSomethingThatUsesConfig(t *testing.T) {
//
//		// make and configure a mocked service.Config
//		mockedConfig := &ConfigMock{
//			HTTPTimeoutFunc: func() time.Duration {
//				panic("mock out the HTTPTimeout method")
//			},
//			TestDataFunc: func() bool {
//				panic("mock out the TestData method")
//			},
//		}
//
//		// use mockedConfig in code that requires service.Config
//		// and then make assertions.
//
//	}
type ConfigMock struct {
	// HTTPTimeoutFunc mocks the HTTPTimeout method.
	HTTPTimeoutFunc func() time.Duration

	// TestDataFunc mocks the TestData method.
	TestDataFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// HTTPTimeout holds details about calls to the HTTPTimeout method.
		HTTPTimeout []struct {
		}
		// TestData holds details about calls to the TestData method.
		TestData []struct {
		}
	}
	lockHTTPTimeout sync.RWMutex
	lockTestData    sync.RWMutex
}

// HTTPTimeout calls HTTPTimeoutFunc.
func (mock *ConfigMock) HTTPTimeout() time.Duration {
	if mock.HTTPTimeoutFunc == nil {
		panic("ConfigMock.HTTPTimeoutFunc: method is nil but Config.HTTPTimeout was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHTTPTimeout.Lock()
	mock.calls.HTTPTimeout = append(mock.calls.HTTPTimeout, callInfo)
	mock.lockHTTPTimeout.Unlock()
	return mock.HTTPTimeoutFunc()
}

// HTTPTimeoutCalls gets all the calls that were made to HTTPTimeout.
// Check the length with:
//
//	len(mockedConfig.HTTPTimeoutCalls())
func (mock *ConfigMock) HTTPTimeoutCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHTTPTimeout.RLock()
	calls = mock.calls.HTTPTimeout
	mock.lockHTTPTimeout.RUnlock()
	return calls
}

// ResetHTTPTimeoutCalls reset all the calls that were made to HTTPTimeout.
func (mock *ConfigMock) ResetHTTPTimeoutCalls() {
	mock.lockHTTPTimeout.Lock()
	mock.calls.HTTPTimeout = nil
	mock.lockHTTPTimeout.Unlock()
}

// TestData calls TestDataFunc.
func (mock *ConfigMock) TestData() bool {
	if mock.TestDataFunc == nil {
		panic("ConfigMock.TestDataFunc: method is nil but Config.TestData was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTestData.Lock()
	mock.calls.TestData = append(mock.calls.TestData, callInfo)
	mock.lockTestData.Unlock()
	return mock.TestDataFunc()
}

// TestDataCalls gets all the calls that were made to TestData.
// Check the length with:
//
//	len(mockedConfig.TestDataCalls())
func (mock *ConfigMock) TestDataCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTestData.RLock()
	calls = mock.calls.TestData
	mock.lockTestData.RUnlock()
	return calls
}

// ResetTestDataCalls reset all the calls that were made to TestData.
func (mock *ConfigMock) ResetTestDataCalls() {
	mock.lockTestData.Lock()
	mock.calls.TestData = nil
	mock.lockTestData.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ConfigMock) ResetCalls() {
	mock.lockHTTPTimeout.Lock()
	mock.calls.HTTPTimeout = nil
	mock.lockHTTPTimeout.Unlock()

	mock.lockTestData.Lock()
	mock.calls.TestData = nil
	mock.lockTestData.Unlock()
}
