// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/feed-relay/rsscast"
	"github.com/feed-relay/smotrim/internal/api"
	"github.com/feed-relay/smotrim/pkg/feed_provider"
)

// AdapterMock is a mock implementation of feed_provider.Adapter.
//
//	func TestSomethingThatUsesAdapter(t *testing.T) {
//
//		// make and configure a mocked feed_provider.Adapter
//		mockedAdapter := &AdapterMock{
//			FeedFunc: func(ctx context.Context, shows []feed_provider.Show, audios map[int]*api.Audio) (*rsscast.Feed, error) {
//				panic("mock out the Feed method")
//			},
//		}
//
//		// use mockedAdapter in code that requires feed_provider.Adapter
//		// and then make assertions.
//
//	}
type AdapterMock struct {
	// FeedFunc mocks the Feed method.
	FeedFunc func(ctx context.Context, shows []feed_provider.Show, audios map[int]*api.Audio) (*rsscast.Feed, error)

	// calls tracks calls to the methods.
	calls struct {
		// Feed holds details about calls to the Feed method.
		Feed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Shows is the shows argument value.
			Shows []feed_provider.Show
			// Audios is the audios argument value.
			Audios map[int]*api.Audio
		}
	}
	lockFeed sync.RWMutex
}

// Feed calls FeedFunc.
func (mock *AdapterMock) Feed(ctx context.Context, shows []feed_provider.Show, audios map[int]*api.Audio) (*rsscast.Feed, error) {
	if mock.FeedFunc == nil {
		panic("AdapterMock.FeedFunc: method is nil but Adapter.Feed was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Shows  []feed_provider.Show
		Audios map[int]*api.Audio
	}{
		Ctx:    ctx,
		Shows:  shows,
		Audios: audios,
	}
	mock.lockFeed.Lock()
	mock.calls.Feed = append(mock.calls.Feed, callInfo)
	mock.lockFeed.Unlock()
	return mock.FeedFunc(ctx, shows, audios)
}

// FeedCalls gets all the calls that were made to Feed.
// Check the length with:
//
//	len(mockedAdapter.FeedCalls())
func (mock *AdapterMock) FeedCalls() []struct {
	Ctx    context.Context
	Shows  []feed_provider.Show
	Audios map[int]*api.Audio
} {
	var calls []struct {
		Ctx    context.Context
		Shows  []feed_provider.Show
		Audios map[int]*api.Audio
	}
	mock.lockFeed.RLock()
	calls = mock.calls.Feed
	mock.lockFeed.RUnlock()
	return calls
}

// ResetFeedCalls reset all the calls that were made to Feed.
func (mock *AdapterMock) ResetFeedCalls() {
	mock.lockFeed.Lock()
	mock.calls.Feed = nil
	mock.lockFeed.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *AdapterMock) ResetCalls() {
	mock.lockFeed.Lock()
	mock.calls.Feed = nil
	mock.lockFeed.Unlock()
}
