// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/feed-relay/smotrim/internal/api"
	"github.com/feed-relay/smotrim/internal/api/graphql"
)

// ClientMock is a mock implementation of feed_provider.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked feed_provider.Client
//		mockedClient := &ClientMock{
//			AudioFunc: func(ctx context.Context, publicID int) (*api.Audio, error) {
//				panic("mock out the Audio method")
//			},
//			BrandEpisodesFunc: func(ctx context.Context, brandID int, perShowLimit int) (*graphql.BrandEpisodes, error) {
//				panic("mock out the BrandEpisodes method")
//			},
//		}
//
//		// use mockedClient in code that requires feed_provider.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// AudioFunc mocks the Audio method.
	AudioFunc func(ctx context.Context, publicID int) (*api.Audio, error)

	// BrandEpisodesFunc mocks the BrandEpisodes method.
	BrandEpisodesFunc func(ctx context.Context, brandID int, perShowLimit int) (*graphql.BrandEpisodes, error)

	// calls tracks calls to the methods.
	calls struct {
		// Audio holds details about calls to the Audio method.
		Audio []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublicID is the publicID argument value.
			PublicID int
		}
		// BrandEpisodes holds details about calls to the BrandEpisodes method.
		BrandEpisodes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BrandID is the brandID argument value.
			BrandID int
			// PerShowLimit is the perShowLimit argument value.
			PerShowLimit int
		}
	}
	lockAudio         sync.RWMutex
	lockBrandEpisodes sync.RWMutex
}

// Audio calls AudioFunc.
func (mock *ClientMock) Audio(ctx context.Context, publicID int) (*api.Audio, error) {
	if mock.AudioFunc == nil {
		panic("ClientMock.AudioFunc: method is nil but Client.Audio was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PublicID int
	}{
		Ctx:      ctx,
		PublicID: publicID,
	}
	mock.lockAudio.Lock()
	mock.calls.Audio = append(mock.calls.Audio, callInfo)
	mock.lockAudio.Unlock()
	return mock.AudioFunc(ctx, publicID)
}

// AudioCalls gets all the calls that were made to Audio.
// Check the length with:
//
//	len(mockedClient.AudioCalls())
func (mock *ClientMock) AudioCalls() []struct {
	Ctx      context.Context
	PublicID int
} {
	var calls []struct {
		Ctx      context.Context
		PublicID int
	}
	mock.lockAudio.RLock()
	calls = mock.calls.Audio
	mock.lockAudio.RUnlock()
	return calls
}

// ResetAudioCalls reset all the calls that were made to Audio.
func (mock *ClientMock) ResetAudioCalls() {
	mock.lockAudio.Lock()
	mock.calls.Audio = nil
	mock.lockAudio.Unlock()
}

// BrandEpisodes calls BrandEpisodesFunc.
func (mock *ClientMock) BrandEpisodes(ctx context.Context, brandID int, perShowLimit int) (*graphql.BrandEpisodes, error) {
	if mock.BrandEpisodesFunc == nil {
		panic("ClientMock.BrandEpisodesFunc: method is nil but Client.BrandEpisodes was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		BrandID      int
		PerShowLimit int
	}{
		Ctx:          ctx,
		BrandID:      brandID,
		PerShowLimit: perShowLimit,
	}
	mock.lockBrandEpisodes.Lock()
	mock.calls.BrandEpisodes = append(mock.calls.BrandEpisodes, callInfo)
	mock.lockBrandEpisodes.Unlock()
	return mock.BrandEpisodesFunc(ctx, brandID, perShowLimit)
}

// BrandEpisodesCalls gets all the calls that were made to BrandEpisodes.
// Check the length with:
//
//	len(mockedClient.BrandEpisodesCalls())
func (mock *ClientMock) BrandEpisodesCalls() []struct {
	Ctx          context.Context
	BrandID      int
	PerShowLimit int
} {
	var calls []struct {
		Ctx          context.Context
		BrandID      int
		PerShowLimit int
	}
	mock.lockBrandEpisodes.RLock()
	calls = mock.calls.BrandEpisodes
	mock.lockBrandEpisodes.RUnlock()
	return calls
}

// ResetBrandEpisodesCalls reset all the calls that were made to BrandEpisodes.
func (mock *ClientMock) ResetBrandEpisodesCalls() {
	mock.lockBrandEpisodes.Lock()
	mock.calls.BrandEpisodes = nil
	mock.lockBrandEpisodes.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ClientMock) ResetCalls() {
	mock.lockAudio.Lock()
	mock.calls.Audio = nil
	mock.lockAudio.Unlock()

	mock.lockBrandEpisodes.Lock()
	mock.calls.BrandEpisodes = nil
	mock.lockBrandEpisodes.Unlock()
}
