// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// FileSizerMock is a mock implementation of feed_provider.FileSizer.
//
//	func TestSomethingThatUsesFileSizer(t *testing.T) {
//
//		// make and configure a mocked feed_provider.FileSizer
//		mockedFileSizer := &FileSizerMock{
//			SizesFunc: func(ctx context.Context, urls []string) map[string]int64 {
//				panic("mock out the Sizes method")
//			},
//		}
//
//		// use mockedFileSizer in code that requires feed_provider.FileSizer
//		// and then make assertions.
//
//	}
type FileSizerMock struct {
	// SizesFunc mocks the Sizes method.
	SizesFunc func(ctx context.Context, urls []string) map[string]int64

	// calls tracks calls to the methods.
	calls struct {
		// Sizes holds details about calls to the Sizes method.
		Sizes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Urls is the urls argument value.
			Urls []string
		}
	}
	lockSizes sync.RWMutex
}

// Sizes calls SizesFunc.
func (mock *FileSizerMock) Sizes(ctx context.Context, urls []string) map[string]int64 {
	if mock.SizesFunc == nil {
		panic("FileSizerMock.SizesFunc: method is nil but FileSizer.Sizes was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Urls []string
	}{
		Ctx:  ctx,
		Urls: urls,
	}
	mock.lockSizes.Lock()
	mock.calls.Sizes = append(mock.calls.Sizes, callInfo)
	mock.lockSizes.Unlock()
	return mock.SizesFunc(ctx, urls)
}

// SizesCalls gets all the calls that were made to Sizes.
// Check the length with:
//
//	len(mockedFileSizer.SizesCalls())
func (mock *FileSizerMock) SizesCalls() []struct {
	Ctx  context.Context
	Urls []string
} {
	var calls []struct {
		Ctx  context.Context
		Urls []string
	}
	mock.lockSizes.RLock()
	calls = mock.calls.Sizes
	mock.lockSizes.RUnlock()
	return calls
}

// ResetSizesCalls reset all the calls that were made to Sizes.
func (mock *FileSizerMock) ResetSizesCalls() {
	mock.lockSizes.Lock()
	mock.calls.Sizes = nil
	mock.lockSizes.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *FileSizerMock) ResetCalls() {
	mock.lockSizes.Lock()
	mock.calls.Sizes = nil
	mock.lockSizes.Unlock()
}
